# Generated by Django 5.0.7 on 2024-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='subscription_start',
            field=models.DateTimeField(),
        ),
    ]
