# Generated by Django 5.0.7 on 2024-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_premiumuser_subscription_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/default_img', null=True, upload_to='media/users'),
        ),
    ]
