# Generated by Django 5.0.7 on 2024-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
