# Generated by Django 5.0.7 on 2024-07-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='premium_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('pro', 'Pro')], max_length=8),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='subscription_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
