# Generated by Django 5.0.7 on 2024-07-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_premiumuser_premium_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/default_img/user_image.png', null=True, upload_to='media/users'),
        ),
    ]
