# Generated by Django 5.0.7 on 2024-07-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='subscription_start',
            field=models.DateTimeField(),
        ),
    ]
