# Generated by Django 5.0.7 on 2024-08-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_premiumuser_subscription_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_img/user_image.png', null=True, upload_to='users'),
        ),
    ]
