from django.urls import path
from . import views

urlpatterns = [
    path('video-lessons/', views.video_lessons_view, name='video_lessons'),
    path('informations/', views.information, name='information'),
    path('birja/', views.birja_view, name='birja'),
    path('information/<int:info_id>/', views.information_detail, name='information_detail'),
    path('advice/', views.advices_view, name='advice'),
    path('signal/', views.signals_view, name='signal'),
    path('news/', views.news_view, name='news'),
    path('analyses/', views.analysis_view, name='analyses'),
    path('notes/', views.note_list, name='note_list'),
    path('notes/create/', views.note_create, name='note_create'),
    path('notes/<int:pk>/edit/', views.note_edit, name='note_edit'),
    path('notes/<int:pk>/delete/', views.note_delete, name='note_delete'),
    path('notes/<int:pk>/', views.note_details, name='note_details'),
    path('lessons/', views.lesson_view, name='lessons'),
    path('lessons/<int:id>/', views.lesson_detail, name='lesson_detail'),
    path('indicators/', views.indicator_view, name='indicators'),
    path('indicators/<int:id>/', views.indicator_detail, name='indicator_detail'),
    path('books/', views.books_view, name='books'),
    path('books/<int:book_id>/', views.book_view, name='book_view'),
    path('mobile/', views.mobile_landing, name='mobile'),
    path('mobile/lessons/', views.mobile_lessons, name='mobile_lessons'),
    path('mobile/lessons/<int:id>/', views.mobile_lesson_detail, name='mobile_lesson_detail'),
    path('mobile/video-lessons/', views.mobile_video_lessons_view, name='mobile_video_lessons'),
    path('mobile/advice/', views.mobile_advices_view, name='mobile_advice'),
    path('mobile/birja/', views.mobile_birja_view, name='mobile_birja'),
    path('mobile/informations/', views.mobile_information, name='mobile_informations'),
    path('mobile/information/<int:info_id>/', views.mobile_information_detail, name='mobile_information_detail'),
    path('mobile/signal/', views.mobile_signals_view, name='mobile_signal'),
    path('mobile/books/', views.mobile_books_view, name='mobile_books'),
    path('mobile/news/', views.mobile_news_view, name='mobile_news'),
    path('mobile/indicators/', views.mobile_indicator_view, name='mobile_indicators'),
    path('mobile/indicators/<int:id>/', views.mobile_indicator_detail, name='mobile_indicator_detail'),
    path('mobile/notes/', views.mobile_note_list, name='mobile_note_list'),
    path('mobile/notes/create/', views.mobile_note_create, name='mobile_note_create'),
    path('mobile/notes/<int:pk>/', views.mobile_note_details, name='mobile_note_details'),
    path('mobile/notes/<int:pk>/edit', views.mobile_note_edit, name='mobile_note_edit'),
    path('mobile/notes/<int:pk>/delete', views.mobile_note_delete, name='mobile_note_delete'),
    path('mobile/analyses/', views.mobile_analysis_view, name='mobile_analyses'),
]
