# Generated by Django 5.0.7 on 2024-08-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info_photo', models.ImageField(upload_to='main/info/')),
                ('info_text', models.TextField()),
            ],
            options={
                'db_table': 'Information',
            },
        ),
        migrations.AlterModelTable(
            name='videolesson',
            table='video_lessons',
        ),
    ]
