# Generated by Django 5.0.7 on 2024-08-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_information_alter_videolesson_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birja_link', models.URLField()),
                ('birja_photo', models.ImageField(upload_to='main/birja/')),
                ('birja_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'birja',
            },
        ),
    ]
