# Generated by Django 5.0.7 on 2024-08-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_birja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_title', models.CharField(max_length=255)),
                ('advice_text', models.TextField()),
            ],
            options={
                'db_table': 'advice',
            },
        ),
    ]
