# Generated by Django 5.0.7 on 2024-08-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('signal_photo', models.ImageField(upload_to='main/signal')),
            ],
            options={
                'db_table': 'signal',
            },
        ),
    ]
