# Generated by Django 5.0.7 on 2024-08-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('news_text', models.TextField()),
                ('news_photo', models.ImageField(upload_to='main/news/')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
