# Generated by Django 5.1 on 2024-08-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('analysis_text', models.TextField()),
                ('analysis_photo', models.ImageField(upload_to='main/analyses/')),
                ('analysis_type', models.CharField(choices=[('normal', 'Normal'), ('standart', 'Standart'), ('pro', 'Pro')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
