# Generated by Django 5.1 on 2024-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lesson_text', models.TextField()),
                ('lesson_photo_1', models.ImageField(upload_to='main/lessons/')),
                ('lesson_photo_2', models.ImageField(upload_to='main/lessons/')),
                ('lesson_type', models.CharField(choices=[('normal', 'Normal'), ('standart', 'Standart'), ('pro', 'Pro')], max_length=30)),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('standart', 'Standart'), ('pro', 'Pro')], max_length=30),
        ),
    ]
