# Generated by Django 5.1 on 2024-08-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_lesson_alter_analysis_analysis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('indicator_text', models.TextField()),
                ('indicator_photo', models.ImageField(upload_to='main/indicators/')),
                ('indicator_type', models.CharField(choices=[('normal', 'Normal'), ('standart', 'Standart'), ('pro', 'Pro')], max_length=30)),
            ],
            options={
                'db_table': 'Indicator',
            },
        ),
    ]
