# Generated by Django 5.1 on 2024-08-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('standard', 'Standard'), ('pro', 'Pro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('standard', 'Standard'), ('pro', 'Pro')], max_length=30),
        ),
    ]
