# Generated by Django 5.1.1 on 2024-10-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_book_book_type_alter_indicator_indicator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='advice_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='advice_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='advice_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='advice_title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='birja',
            name='birja_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='birja',
            name='birja_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='info_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='info_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
