# Generated by Django 5.1.1 on 2024-12-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_advice_advice_text_ru_advice_advice_text_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='note',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title_uz',
        ),
    ]
