# Generated by Django 5.0.7 on 2024-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feargreedindex',
            name='image',
            field=models.ImageField(upload_to='main/home'),
        ),
    ]
