# Generated by Django 5.0.7 on 2024-08-11 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_feargreedindex_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feargreedindex',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
